In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
corpus=["There was a little girl",
       "Who had a little curl",
       "Right in the middle of her forehead.",
       "When she was good",
       "She was very very good"]

In [3]:
corpus

['There was a little girl',
 'Who had a little curl',
 'Right in the middle of her forehead.',
 'When she was good',
 'She was very very good']

In [4]:
vectorize=CountVectorizer()

In [7]:
X=vectorize.fit_transform(corpus)

In [8]:
X

<5x18 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [9]:
X.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0]],
      dtype=int64)

In [10]:
vectorize.get_feature_names()

['curl',
 'forehead',
 'girl',
 'good',
 'had',
 'her',
 'in',
 'little',
 'middle',
 'of',
 'right',
 'she',
 'the',
 'there',
 'very',
 'was',
 'when',
 'who']

In [23]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [24]:
X=vectorizer2.fit_transform(corpus)

In [25]:
vectorizer2.get_feature_names()

['had little',
 'her forehead',
 'in the',
 'little curl',
 'little girl',
 'middle of',
 'of her',
 'right in',
 'she was',
 'the middle',
 'there was',
 'very good',
 'very very',
 'was good',
 'was little',
 'was very',
 'when she',
 'who had']

In [26]:
X.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0]],
      dtype=int64)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
tf_vector=TfidfVectorizer()

In [29]:
X=tf_vector.fit_transform(corpus)

In [30]:
X.toarray()

array([[0.        , 0.        , 0.56801408, 0.        , 0.        ,
        0.        , 0.        , 0.45827018, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.56801408, 0.        ,
        0.38040565, 0.        , 0.        ],
       [0.52335825, 0.        , 0.        , 0.        , 0.52335825,
        0.        , 0.        , 0.42224214, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.52335825],
       [0.        , 0.37796447, 0.        , 0.        , 0.        ,
        0.37796447, 0.37796447, 0.        , 0.37796447, 0.37796447,
        0.37796447, 0.        , 0.37796447, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.48648432, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.48648432, 0.        , 0.        , 0.        ,
        0.40382593, 0.60298477, 0.        ],
    

In [31]:
tf_vector.get_feature_names()

['curl',
 'forehead',
 'girl',
 'good',
 'had',
 'her',
 'in',
 'little',
 'middle',
 'of',
 'right',
 'she',
 'the',
 'there',
 'very',
 'was',
 'when',
 'who']